[tool.black]
# Do not enable `verbose = true` unless Black changes their behavior to respect
# `--quiet` on the command line properly
# verbose = true
line-length = 80
skip-string-normalization = true
[tool.isort]
profile = "black"
known_first_party = "kobo"
no_lines_before = ["LOCALFOLDER"]

[tool.mypy]
exclude = [
    "env/src/django-digest",
    "env/src/formpack",
    "env/src/kobo-service-account",
    "env/src/python-digest"
]
[tool.django-stubs]
django_settings_module = "kobo.settings"
