[tool.black]
# Do not enable `verbose = true` unless Black changes their behavior to respect
# `--quiet` on the command line properly
# verbose = true
line-length = 80
skip-string-normalization = true
[tool.isort]
profile = "black"
known_first_party = "kobo"
no_lines_before = ["LOCALFOLDER"]

[tool.ruff.format]
quote-style = "single"
[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
# Exclude virtual environment projects that cause mypy to error
exclude = [
    "src/django-digest",
    "src/formpack",
    "src/kobo-service-account",
    "src/python-digest"
]
[tool.django-stubs]
django_settings_module = "kobo.settings"
