---
aws_region: us-east-1
environmentVariables:
  PUBLIC_REQUEST_SCHEME: http
  PUBLIC_DOMAIN_NAME: dev.veritree.com
  KOBOCAT_PUBLIC_SUBDOMAIN: kc
  KOBOFORM_PUBLIC_SUBDOMAIN: kf
  ENKETO_EXPRESS_PUBLIC_SUBDOMAIN: ee
  INTERNAL_DOMAIN_NAME: veritree
  KOBO_SUPPORT_EMAIL: system@veritree.org

  POSTGRES_PORT: 5432
  POSTGRES_HOST: dev-koboform.cluster-cxqhyxx46hk7.us-east-1.rds.amazonaws.com
  KPI_POSTGRES_DB: koboform

  KPI_DEFAULT_FILE_STORAGE: storages.backends.s3boto3.S3Boto3Storage
  KPI_AWS_STORAGE_BUCKET_NAME: kf.dev.veritree.com

  GOOGLE_ANALYTICS_TOKEN: ""
  KPI_RAVEN_DSN: ""
  KPI_RAVEN_JS_DSN: ""

  EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  EMAIL_HOST: email-smtp.us-east-2.amazonaws.com
  EMAIL_PORT: 587
  EMAIL_USE_TLS: True
  DEFAULT_FROM_EMAIL: system@veritree.org

  KF_WEB_SERVER: uWSGI
  VERITREE_KC_WEB_SERVER: uWSGI
  KPI_STATIC_FILES_SERVER: Nginx
  ENKETO_PROTOCOL: http
  KPI_PORT: 8003
  NGINX_PUBLIC_PORT: 80

  DEBUG: True
  TEMPLATE_DEBUG: "True"
  ENV: "dev"
  KPI_DJANGO_DEBUG: "True"
  DJANGO_DEBUG: "True"
  ENKETO_VERSION: Express
  KPI_PREFIX: /
  KPI_MONGO_HOST: kb-dev-formhub.cluster-cxqhyxx46hk7.us-east-1.docdb.amazonaws.com
  KPI_MONGO_PORT: 27017
  KPI_MONGO_NAME: formhub
  KPI_MONGO_USER: kobo

  DJANGO_LANGUAGE_CODES: en ar es fr hi ku pl pt zh-hans
  C_FORCE_ROOT: True
  SYNC_KOBOCAT_XFORMS: True # Should be True on at least one frontend environment
  KPI_UWSGI_MAX_REQUESTS: 512
  KPI_UWSGI_WORKERS_COUNT: 2
  KPI_UWSGI_CHEAPER_RSS_LIMIT_SOFT: 134217728
  KPI_UWSGI_CHEAPER_WORKERS_COUNT: 1
  KPI_UWSGI_HARAKIRI: 120
  KPI_UWSGI_WORKER_RELOAD_MERCY: 120

  UWSGI_PASS_TIMEOUT: 130
  TEMPLATED_VAR_REFS: $${PUBLIC_REQUEST_SCHEME} $${INTERNAL_DOMAIN_NAME} $${PUBLIC_DOMAIN_NAME} $${KOBOFORM_PUBLIC_SUBDOMAIN} $${KOBOCAT_PUBLIC_SUBDOMAIN} $${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}

  VERITREE_OAUTH_CLIENT_ID: 5
  VERITREE_HOOKS_EMAIL: monitoring.hooks@veritree.com

secrets:
  - key: "/kubernetes/dev/kobo/app"
    name: "KOBO_SUPERUSER_USERNAME"
    property: "KOBO_SUPERUSER_USERNAME"

  - key: "/kubernetes/dev/kobo/app"
    name: "KOBO_SUPERUSER_PASSWORD"
    property: "KOBO_SUPERUSER_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "ENKETO_API_TOKEN"
    property: "ENKETO_API_TOKEN"

  - key: "/kubernetes/dev/kobo/app"
    name: "DJANGO_SECRET_KEY"
    property: "DJANGO_SECRET_KEY"

  - key: "/kubernetes/dev/kobo/app"
    name: "POSTGRES_USER"
    property: "POSTGRES_USER"

  - key: "/kubernetes/dev/kobo/app"
    name: "POSTGRES_PASSWORD"
    property: "POSTGRES_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "KPI_BROKER_URL"
    property: "KPI_BROKER_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "KPI_MONGO_PASS"
    property: "KPI_MONGO_PASS"

  - key: "/kubernetes/dev/kobo/app"
    name: "VERITREE_OAUTH_CLIENT_SECRET"
    property: "VERITREE_OAUTH_CLIENT_SECRET"

  - key: "/kubernetes/dev/kobo/app"
    name: "VERITREE_HOOKS_EMAIL_PASSWORD"
    property: "VERITREE_HOOKS_EMAIL_PASSWORD"

  - key: "/kubernetes/dev/kobo/app"
    name: "KC_DATABASE_URL"
    property: "KC_DATABASE_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "KPI_DATABASE_URL"
    property: "KPI_DATABASE_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "REDIS_SESSION_URL"
    property: "REDIS_SESSION_URL"

  - key: "/kubernetes/dev/kobo/app"
    name: "AWS_ACCESS_KEY_ID"
    property: "AWS_ACCESS_KEY_ID"

  - key: "/kubernetes/dev/kobo/app"
    name: "AWS_SECRET_ACCESS_KEY"
    property: "AWS_SECRET_ACCESS_KEY"

  - key: "/kubernetes/dev/kobo/app"
    name: "EMAIL_HOST_USER"
    property: "EMAIL_HOST_USER"

  - key: "/kubernetes/dev/kobo/app"
    name: "EMAIL_HOST_PASSWORD"
    property: "EMAIL_HOST_PASSWORD"

clusterIssuer: letsencrypt-dev

serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::311934536039:role/kobo-dev"

volume:
  media:
    size: 50Gi
    efsId: fs-06b89915e1acd1fcf::fsap-079b5c5d895ab8357

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    alb.ingress.kubernetes.io/tags: EKS=True
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: "veritree-kb-dev"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  hosts:
    - host: kf.dev.veritree.com
      paths:
        - /*
  tls:
    - hosts:
        - kf.dev.veritree.com
      secretName: veritree-kobo-dev-cert
